### PR TITLE
Remove elm-tooling.json

### PR DESCRIPTION
**Pull request by lydell**
https://github.com/elm-tooling/elm-language-server/pull/629 removes the need for `"entrypoints"` in elm-tooling.json. That’s the only thing we used in elm-tooling.json, so we can remove it now.

If the language server needs configuration in the future, I would recommend:

- Choose a file name that makes it obvious what it is for, like `elm-language-server.json`.
- Use some other format than JSON if it makes sense.
- Provide a schema for it.
- Include a CLI `init` command that can create a new one.

After more than a year of elm-tooling.json, we still haven’t found any configuration that more than 1 tool use, so the whole idea of it is very over engineered. If we ever find the need for shared configuration in the future, I’m sure we’ll figure out a much better solution then.

### CODE REVIEW

**Comment by razzeee** [comment]
Can you update this?

**Comment by lydell** [comment]
What would you like to be updated?

**Comment by razzeee** [comment]
I guess using the schema for the remaining fields wouldn't make much senes, as you want people to change the file via cli?

**Comment by lydell** [comment]
Correct! I want people to use the CLI, and even when they don’t I don’t think a schema helps much for the `"tools"` since all the keys are dynamic.

**Pull request merged**
