### PR TITLE
Add elm-analyse schema

### PR DESCRIPTION
**Pull request by Razzeee**
Kinda depends on https://github.com/elm-tooling/elm-language-server/pull/614

### CODE REVIEW

**Comment by Razzeee** [comment]
We might not want to do this, but do https://github.com/elm-tooling/elm-language-server/issues/616 instead.

**Comment by jmbockhorst** [comment]
I agree.

**Comment by lydell** [comment]
If the schema in this PR is correct, maybe merge anyway since it adds value until the config is moved?

**Comment by Razzeee** [comment]
It would, but that would have to be released, to add value.

**Pull request merged**
